<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Teacher;
use App\Models\School;

class TeacherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $schools = School::pluck('id')->toArray();

        $teachers = [
            [
                'name' => 'Maria Silva Santos',
                'email' => 'maria.silva@escola.com',
                'phone' => '11999887766',
                'cpf' => '12345678901',
                'rg' => '12345678',
                'birth_date' => '1985-03-15',
                'gender' => 'feminino',
                'registration' => 'T001',
                'specialty' => 'Matemática',
                'degree' => 'Licenciatura em Matemática',
                'institution' => 'Universidade de São Paulo',
                'graduation_year' => 2008,
                'status' => 'ativo',
                'street' => 'Rua das Flores',
                'number' => '123',
                'complement' => 'Apto 45',
                'neighborhood' => 'Centro',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '01234567',
                'hiring_date' => '2010-02-01',
                'contract_type' => 'efetivo',
                'salary' => 3500.00,
                'workload' => '40h semanais',
                'observations' => 'Professora dedicada com excelente didática',
                'subjects' => ['Matemática', 'Física'],
                'schools' => array_slice($schools, 0, 2),
            ],
            [
                'name' => 'João Carlos Oliveira',
                'email' => 'joao.oliveira@escola.com',
                'phone' => '11988776655',
                'cpf' => '98765432109',
                'rg' => '87654321',
                'birth_date' => '1978-07-22',
                'gender' => 'masculino',
                'registration' => 'T002',
                'specialty' => 'História',
                'degree' => 'Licenciatura em História',
                'institution' => 'Universidade Estadual de Campinas',
                'graduation_year' => 2002,
                'status' => 'ativo',
                'street' => 'Avenida Paulista',
                'number' => '1000',
                'complement' => 'Sala 200',
                'neighborhood' => 'Bela Vista',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '01310100',
                'hiring_date' => '2005-03-15',
                'contract_type' => 'efetivo',
                'salary' => 4200.00,
                'workload' => '40h semanais',
                'observations' => 'Especialista em História do Brasil',
                'subjects' => ['História', 'Geografia'],
                'schools' => array_slice($schools, 0, 1),
            ],
            [
                'name' => 'Ana Paula Ferreira',
                'email' => 'ana.ferreira@escola.com',
                'phone' => '11977665544',
                'cpf' => '45678912301',
                'rg' => '45678912',
                'birth_date' => '1990-11-08',
                'gender' => 'feminino',
                'registration' => 'T003',
                'specialty' => 'Português',
                'degree' => 'Licenciatura em Letras',
                'institution' => 'Universidade Federal de São Paulo',
                'graduation_year' => 2013,
                'status' => 'ativo',
                'street' => 'Rua Augusta',
                'number' => '500',
                'complement' => 'Apto 12',
                'neighborhood' => 'Consolação',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '01305000',
                'hiring_date' => '2015-08-01',
                'contract_type' => 'contratado',
                'salary' => 2800.00,
                'workload' => '30h semanais',
                'observations' => 'Jovem professora com muita vontade de ensinar',
                'subjects' => ['Português', 'Literatura', 'Redação'],
                'schools' => array_slice($schools, 1, 2),
            ],
            [
                'name' => 'Roberto Almeida Costa',
                'email' => 'roberto.costa@escola.com',
                'phone' => '11966554433',
                'cpf' => '78912345601',
                'rg' => '78912345',
                'birth_date' => '1965-12-03',
                'gender' => 'masculino',
                'registration' => 'T004',
                'specialty' => 'Educação Física',
                'degree' => 'Licenciatura em Educação Física',
                'institution' => 'Universidade de Brasília',
                'graduation_year' => 1988,
                'status' => 'aposentado',
                'street' => 'Rua dos Pinheiros',
                'number' => '789',
                'complement' => 'Casa',
                'neighborhood' => 'Pinheiros',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '05422000',
                'hiring_date' => '1990-01-15',
                'contract_type' => 'efetivo',
                'salary' => 0.00,
                'workload' => 'Aposentado',
                'observations' => 'Professor aposentado, mas ainda colabora com projetos esportivos',
                'subjects' => ['Educação Física'],
                'schools' => array_slice($schools, 0, 1),
            ],
            [
                'name' => 'Fernanda Lima Rodrigues',
                'email' => 'fernanda.rodrigues@escola.com',
                'phone' => '11955443322',
                'cpf' => '32165498701',
                'rg' => '32165498',
                'birth_date' => '1982-05-18',
                'gender' => 'feminino',
                'registration' => 'T005',
                'specialty' => 'Ciências',
                'degree' => 'Licenciatura em Ciências Biológicas',
                'institution' => 'Universidade Estadual Paulista',
                'graduation_year' => 2006,
                'status' => 'ativo',
                'street' => 'Rua das Palmeiras',
                'number' => '456',
                'complement' => 'Apto 78',
                'neighborhood' => 'Vila Madalena',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '05433000',
                'hiring_date' => '2008-06-01',
                'contract_type' => 'efetivo',
                'salary' => 3800.00,
                'workload' => '40h semanais',
                'observations' => 'Especialista em laboratório de ciências',
                'subjects' => ['Ciências', 'Biologia'],
                'schools' => array_slice($schools, 0, 3),
            ],
            [
                'name' => 'Carlos Eduardo Santos',
                'email' => 'carlos.santos@escola.com',
                'phone' => '11944332211',
                'cpf' => '14725836901',
                'rg' => '14725836',
                'birth_date' => '1975-09-25',
                'gender' => 'masculino',
                'registration' => 'T006',
                'specialty' => 'Inglês',
                'degree' => 'Licenciatura em Letras - Inglês',
                'institution' => 'Pontifícia Universidade Católica de São Paulo',
                'graduation_year' => 1999,
                'status' => 'ativo',
                'street' => 'Rua dos Ciprestes',
                'number' => '321',
                'complement' => 'Apto 15',
                'neighborhood' => 'Jardins',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '01223000',
                'hiring_date' => '2001-02-01',
                'contract_type' => 'efetivo',
                'salary' => 4500.00,
                'workload' => '40h semanais',
                'observations' => 'Professor com certificação internacional em inglês',
                'subjects' => ['Inglês', 'Espanhol'],
                'schools' => array_slice($schools, 1, 2),
            ],
            [
                'name' => 'Lucia Helena Martins',
                'email' => 'lucia.martins@escola.com',
                'phone' => '11933221100',
                'cpf' => '96385274101',
                'rg' => '96385274',
                'birth_date' => '1988-04-12',
                'gender' => 'feminino',
                'registration' => 'T007',
                'specialty' => 'Arte',
                'degree' => 'Licenciatura em Artes Visuais',
                'institution' => 'Universidade de São Paulo',
                'graduation_year' => 2011,
                'status' => 'ativo',
                'street' => 'Rua das Acácias',
                'number' => '654',
                'complement' => 'Apto 23',
                'neighborhood' => 'Moema',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '04012000',
                'hiring_date' => '2012-03-01',
                'contract_type' => 'contratado',
                'salary' => 3000.00,
                'workload' => '30h semanais',
                'observations' => 'Artista plástica com trabalhos expostos em galerias',
                'subjects' => ['Arte', 'História da Arte'],
                'schools' => array_slice($schools, 0, 2),
            ],
            [
                'name' => 'Pedro Henrique Silva',
                'email' => 'pedro.silva@escola.com',
                'phone' => '11922110099',
                'cpf' => '85296374101',
                'rg' => '85296374',
                'birth_date' => '1992-01-30',
                'gender' => 'masculino',
                'registration' => 'T008',
                'specialty' => 'Informática',
                'degree' => 'Tecnólogo em Sistemas de Informação',
                'institution' => 'FATEC',
                'graduation_year' => 2014,
                'status' => 'ativo',
                'street' => 'Rua das Orquídeas',
                'number' => '987',
                'complement' => 'Apto 67',
                'neighborhood' => 'Vila Prudente',
                'city' => 'São Paulo',
                'state' => 'SP',
                'postal_code' => '03164000',
                'hiring_date' => '2016-01-01',
                'contract_type' => 'temporario',
                'salary' => 2500.00,
                'workload' => '25h semanais',
                'observations' => 'Especialista em programação e robótica educacional',
                'subjects' => ['Informática', 'Programação'],
                'schools' => array_slice($schools, 1, 1),
            ],
        ];

        foreach ($teachers as $teacherData) {
            Teacher::create($teacherData);
        }
    }
}
